export const Imgs = [
    {
        name: "",
        data: {
            user: "",
            userIcon: "/imgs/user_icon/user_icon.jpg",
            state: true,
            size: "",
            messagesNumber: "",
            url: "/imgs/img_1.jpg",
            colors: ["#658CA9", "#FFCC99", "#009966", "#294779",],
            tags: [],
        },
    }, {
        name: "",
        data: {
            user: "",
            userIcon: "/imgs/user_icon/user_icon.jpg",
            state: false,
            size: "",
            messagesNumber: "",
            url: "/imgs/img_2.jpg",
            colors: ["#658CA9", "#FFCC99", "#009966", "#294779",],
            tags: [],
        },
    }, {
        name: "",
        data: {
            user: "",
            userIcon: "/imgs/user_icon/user_icon.jpg",
            state: false,
            size: "",
            messagesNumber: "",
            url: "/imgs/img_3.jpg",
            colors: ["#658CA9", "#FFCC99", "#009966", "#294779",],
            tags: [],
        },
    }, {
        name: "",
        data: {
            user: "",
            userIcon: "/imgs/user_icon/user_icon.jpg",
            state: false,
            size: "",
            messagesNumber: "",
            url: "/imgs/img_4.png",
            colors: ["#658CA9", "#FFCC99", "#009966", "#294779",],
            tags: [],
        },
    }, {
        name: "",
        data: {
            user: "",
            userIcon: "/imgs/user_icon/user_icon.jpg",
            state: false,
            size: "",
            messagesNumber: "",
            url: "/imgs/img_4.png",
            colors: ["#658CA9", "#FFCC99", "#009966", "#294779",],
            tags: [],
        },
    }, {
        name: "",
        data: {
            user: "",
            userIcon: "/imgs/user_icon/user_icon.jpg",
            state: false,
            size: "",
            messagesNumber: "",
            url: "/imgs/img_5.png",
            colors: ["#658CA9", "#FFCC99", "#009966", "#294779",],
            tags: [],
        },
    }, {
        name: "",
        data: {
            user: "",
            userIcon: "/imgs/user_icon/user_icon.jpg",
            state: false,
            size: "",
            messagesNumber: "",
            url: "/imgs/img_7.jpg",
            colors: ["#658CA9", "#FFCC99", "#009966", "#294779",],
            tags: [],
        },
    }, {
        name: "",
        data: {
            user: "",
            userIcon: "/imgs/user_icon/user_icon.jpg",
            state: false,
            size: "",
            messagesNumber: "",
            url: "/imgs/img_6.jpg",
            colors: ["#658CA9", "#FFCC99", "#009966", "#294779",],
            tags: [],
        },
    }, {
        name: "",
        data: {
            user: "",
            userIcon: "/imgs/user_icon/user_icon.jpg",
            state: false,
            size: "",
            messagesNumber: "",
            url: "/imgs/img_6.jpg",
            colors: ["#658CA9", "#FFCC99", "#009966", "#294779",],
            tags: [],
        },
    }, {
        name: "",
        data: {
            user: "",
            userIcon: "/imgs/user_icon/user_icon.jpg",
            state: false,
            size: "",
            messagesNumber: "",
            url: "/imgs/img_6.jpg",
            colors: ["#658CA9", "#FFCC99", "#009966", "#294779",],
            tags: [],
        },
    }, {
        name: "",
        data: {
            user: "",
            userIcon: "/imgs/user_icon/user_icon.jpg",
            state: false,
            size: "",
            messagesNumber: "",
            url: "/imgs/img_6.jpg",
            colors: ["#658CA9", "#FFCC99", "#009966", "#294779",],
            tags: [],
        },
    },{
        name: "",
        data: {
            user: "",
            userIcon: "/imgs/user_icon/user_icon.jpg",
            state: true,
            size: "",
            messagesNumber: "",
            url: "/imgs/img_1.jpg",
            colors: ["#658CA9", "#FFCC99", "#009966", "#294779",],
            tags: [],
        },
    },{
        name: "",
        data: {
            user: "",
            userIcon: "/imgs/user_icon/user_icon.jpg",
            state: true,
            size: "",
            messagesNumber: "",
            url: "/imgs/img_1.jpg",
            colors: ["#658CA9", "#FFCC99", "#009966", "#294779",],
            tags: [],
        },
    },{
        name: "",
        data: {
            user: "",
            userIcon: "/imgs/user_icon/user_icon.jpg",
            state: true,
            size: "",
            messagesNumber: "",
            url: "/imgs/img_1.jpg",
            colors: ["#658CA9", "#FFCC99", "#009966", "#294779",],
            tags: [],
        },
    },{
        name: "",
        data: {
            user: "",
            userIcon: "/imgs/user_icon/user_icon.jpg",
            state: true,
            size: "",
            messagesNumber: "",
            url: "/imgs/img_1.jpg",
            colors: ["#658CA9", "#FFCC99", "#009966", "#294779",],
            tags: [],
        },
    },{
        name: "",
        data: {
            user: "",
            userIcon: "/imgs/user_icon/user_icon.jpg",
            state: true,
            size: "",
            messagesNumber: "",
            url: "/imgs/img_1.jpg",
            colors: ["#658CA9", "#FFCC99", "#009966", "#294779",],
            tags: [],
        },
    },{
        name: "",
        data: {
            user: "",
            userIcon: "/imgs/user_icon/user_icon.jpg",
            state: true,
            size: "",
            messagesNumber: "",
            url: "/imgs/img_1.jpg",
            colors: ["#658CA9", "#FFCC99", "#009966", "#294779",],
            tags: [],
        },
    },{
        name: "",
        data: {
            user: "",
            userIcon: "/imgs/user_icon/user_icon.jpg",
            state: true,
            size: "",
            messagesNumber: "",
            url: "/imgs/img_1.jpg",
            colors: ["#658CA9", "#FFCC99", "#009966", "#294779",],
            tags: [],
        },
    },{
        name: "",
        data: {
            user: "",
            userIcon: "/imgs/user_icon/user_icon.jpg",
            state: true,
            size: "",
            messagesNumber: "",
            url: "/imgs/img_1.jpg",
            colors: ["#658CA9", "#FFCC99", "#009966", "#294779",],
            tags: [],
        },
    },{
        name: "",
        data: {
            user: "",
            userIcon: "/imgs/user_icon/user_icon.jpg",
            state: true,
            size: "",
            messagesNumber: "",
            url: "/imgs/img_1.jpg",
            colors: ["#658CA9", "#FFCC99", "#009966", "#294779",],
            tags: [],
        },
    },{
        name: "",
        data: {
            user: "",
            userIcon: "/imgs/user_icon/user_icon.jpg",
            state: true,
            size: "",
            messagesNumber: "",
            url: "/imgs/img_1.jpg",
            colors: ["#658CA9", "#FFCC99", "#009966", "#294779",],
            tags: [],
        },
    },{
        name: "",
        data: {
            user: "",
            userIcon: "/imgs/user_icon/user_icon.jpg",
            state: true,
            size: "",
            messagesNumber: "",
            url: "/imgs/img_1.jpg",
            colors: ["#658CA9", "#FFCC99", "#009966", "#294779",],
            tags: [],
        },
    },
];